// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smvuusdoipaywvbqernt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdnV1c2RvaXBheXd2YnFlcm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDk3MjQsImV4cCI6MjA2NDEyNTcyNH0.qopjw_XkBe6S96xyebdnV-kG-uBX9-09fMlphgH68Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);